version: '2.1'

services:

  myproject-web:
    container_name: myproject-web
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "12100:80"
    volumes:
      - ../application:/app
    links:
      - myproject-mysql
    depends_on:
      myproject-mysql:
        condition: service_healthy
    env_file:
      - .env-dev

  myproject-mysql:
    container_name: myproject-mysql
    image: mysql:5.7
    ports:
      - "12200:3306"
    env_file:
      - .env-dev
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
